module.exports = {
  TEXT_TASKS: [
    {
      content: "احصل على 1000 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 1000,
      reward: {
        xp: 25,
        coins: 5,
      },
      difficulty: 1,
    },
    {
      content: "احصل على 1500 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 1500,
      reward: {
        xp: 50,
        coins: 10,
      },
      difficulty: 1,
    },
    {
      content: "احصل على 2000 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 2000,
      reward: {
        xp: 100,
        coins: 15,
      },
      difficulty: 1,
    },
    {
      content: "احصل على 2500 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 2500,
      reward: {
        xp: 125,
        coins: 20,
      },
      difficulty: 2,
    },
    {
      content: "احصل على 3000 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 3000,
      reward: {
        xp: 150,
        coins: 25,
      },
      difficulty: 2,
    },
    {
      content: "احصل على 3500 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 3500,
      reward: {
        xp: 200,
        coins: 30,
      },
      difficulty: 2,
    },
    {
      content: "احصل على 4000 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 4000,
      reward: {
        xp: 250,
        coins: 35,
      },
      difficulty: 3,
    },
    {
      content: "احصل على 4500 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 4500,
      reward: {
        xp: 300,
        coins: 40,
      },
      difficulty: 3,
    },
    {
      content: "احصل على 5000 اكس بي في التوب اليومي",
      done: false,
      type: "text",
      target: 5000,
      reward: {
        xp: 325,
        coins: 45,
      },
      difficulty: 3,
    },
  ],
  VOICE_TASKS: [
    {
      content: "اجلس ساعة في روم الصوت",
      done: false,
      type: "voice",
      target: 1,
      reward: {
        xp: 30,
        coins: 6,
      },
      difficulty: 1,
    },
    {
      content: "اجلس ساعتين في روم الصوت",
      done: false,
      type: "voice",
      target: 2,
      reward: {
        xp: 60,
        coins: 12,
      },
      difficulty: 1,
    },
    {
      content: "اجلس 3 ساعات في روم الصوت",
      done: false,
      type: "voice",
      target: 2,
      reward: {
        xp: 90,
        coins: 18,
      },
      difficulty: 2,
    },
    {
      content: "اجلس 4 ساعات في روم الصوت",
      done: false,
      type: "voice",
      target: 4,
      reward: {
        xp: 120,
        coins: 24,
      },
      difficulty: 2,
    },
    {
      content: "اجلس 5 ساعات في روم الصوت",
      done: false,
      type: "voice",
      target: 2,
      reward: {
        xp: 150,
        coins: 30,
      },
      difficulty: 3,
    },
  ],
  MESSAGES_TASKS: [
    {
      content: "ارسل 500 رسالة اليوم",
      done: false,
      type: "messages",
      target: 500,
      reward: {
        xp: 25,
        coins: 5,
      },
      difficulty: 1,
    },
    {
      content: "ارسل 600 رسالة اليوم",
      done: false,
      type: "messages",
      target: 600,
      reward: {
        xp: 50,
        coins: 10,
      },
      difficulty: 1,
    },
    {
      content: "ارسل 700 رسالة اليوم",
      done: false,
      type: "messages",
      target: 700,
      reward: {
        xp: 75,
        coins: 12,
      },
      difficulty: 2,
    },
    {
      content: "ارسل 800 رسالة اليوم",
      done: false,
      type: "messages",
      target: 800,
      reward: {
        xp: 100,
        coins: 18,
      },
      difficulty: 3,
    },
  ],
  RANDOM_TASKS: [
    {
      content: "ادعُ صديق للسيرفر",
      done: false,
      type: "random",
      target: 0,
      reward: {
        xp: 50,
        coins: 10,
      },
      difficulty: 1,
    },
    {
      content: "شارك صورة GIF في الشات",
      done: false,
      type: "random",
      target: 0,
      reward: {
        xp: 60,
        coins: 12,
      },
      difficulty: 1,
    },
    {
      content: "ارسل فيديو في روم الميمز",
      done: false,
      type: "random",
      target: 0,
      reward: {
        xp: 70,
        coins: 14,
      },
      difficulty: 1,
    },

    {
      content: "شارك في المنطقة الإبداعية",
      done: false,
      type: "random",
      target: 0,
      reward: {
        xp: 80,
        coins: 16,
      },
      difficulty: 2,
    },
    {
      content: "تفاعل مع 5 رسائل مختلفة",
      done: false,
      type: "random",
      target: 0,
      reward: {
        xp: 90,
        coins: 18,
      },
      difficulty: 2,
    },
    {
      content: "شارك محتوى في الميديا",
      done: false,
      type: "random",
      target: 0,
      reward: {
        xp: 100,
        coins: 20,
      },
      difficulty: 3,
    },
    {
      content: "اقترح فكرة لصناع المحتوى بروم الأفكار",
      done: false,
      type: "random",
      target: 0,
      reward: {
        xp: 120,
        coins: 25,
      },
      difficulty: 3,
    },
  ],
  ACHIEVEMENTS: [
    {
      content: "100 رسالة",
      type: "text",
      target: 100,
      reward: 10,
    },
    {
      content: "500 رسالة",
      type: "text",
      target: 500,
      reward: 100,
    },
    {
      content: "1000 رسالة",
      type: "text",
      target: 1000,
      reward: 150,
    },
    {
      content: "5000 رسالة",
      type: "text",
      target: 5000,
      reward: 550,
    },
    {
      content: "10000 رسالة",
      type: "text",
      target: 10000,
      reward: 1000,
    },
    {
      content: "50000 رسالة",
      type: "text",
      target: 50000,
      reward: 3500,
    },
    {
      content: "100000 رسالة",
      type: "text",
      target: 100000,
      reward: 5500,
    },

    {
      content: "100 دقيقة صوتية",
      type: "voice",
      target: 100,
      reward: 10,
    },
    {
      content: "500 دقيقة صوتية",
      type: "voice",
      target: 500,
      reward: 30,
    },
    {
      content: "1000 دقيقة صوتية",
      type: "voice",
      target: 1000,
      reward: 85,
    },
    {
      content: "5000 دقيقة صوتية",
      type: "voice",
      target: 5000,
      reward: 250,
    },
    {
      content: "10000 دقيقة صوتية",
      type: "voice",
      target: 10000,
      reward: 950,
    },
    {
      content: "50000 دقيقة صوتية",
      type: "voice",
      target: 50000,
      reward: 3000,
    },
    {
      content: "100000 دقيقة صوتية",
      type: "voice",
      target: 100000,
      reward: 4500,
    },
  ],
  SHOP_ITEMS: [
    {
      id: 1,
      price: 500,
      content: "إيموجيات عامة",
      description: "فتح استخدام الإيموجيات العامة",
      time: null,
      priority: 25,
      category: "general",
      emoji: "😊",
    },
    {
      id: 2,
      price: 850,
      content: "صور متحركة",
      description: "إرسال الصور المتحركة",
      time: null,
      priority: 25,
      category: "general",
      emoji: "🎞️",
    },
    {
      id: 3,
      price: 1100,
      content: "الوسائط في الشات العام",
      description: "إرسال الوسائط داخل الشات العام",
      time: null,
      priority: 25,
      category: "general",
      emoji: "🖼️",
    },
    {
      id: 4,
      price: 1250,
      content: "إضافة إيموجي أو ستيكر",
      description: "إضافة إيموجيات أو ستيكرات للسيرفر",
      time: null,
      priority: 25,
      category: "general",
      emoji: "➕",
    },
    {
      id: 5,
      price: 1750,
      content: "بث شاشة مباشر",
      description: "فتح خاصية بث الشاشة المباشر",
      time: null,
      priority: 25,
      category: "general",
      emoji: "🖥️",
    },
    {
      id: 6,
      price: 2000,
      content: "رياكشن على الرسائل",
      description: "إضافة رياكشنات على الرسائل",
      time: null,
      priority: 25,
      category: "general",
      emoji: "👍",
    },
    {
      id: 7,
      price: 3000,
      content: "الألوان العادية",
      description: "تخصيص لون عادي",
      time: null,
      priority: 25,
      category: "general",
      emoji: "🎨",
    },
    {
      id: 8,
      price: 5000,
      content: "الألوان المميزة",
      description: "تخصيص لون مميز",
      time: null,
      priority: 25,
      category: "general",
      emoji: "🌈",
    },

    {
      id: 9,
      price: 50,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "5m",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 10,
      price: 100,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "10m",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 11,
      price: 150,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "15m",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 12,
      price: 200,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "20m",
      priority: 40,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 13,
      price: 250,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "25m",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 14,
      price: 300,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "30m",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 15,
      price: 1000,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "1h",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 16,
      price: 2000,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "2h",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 17,
      price: 3000,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "3h",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 18,
      price: 6000,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "6h",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },
    {
      id: 19,
      price: 12000,
      content: "دبل اكس بي فويس",
      description: "مضاعفة نقاط الخبرة من الصوت",
      time: "12h",
      priority: 75,
      category: "voice",
      emoji: "🎤",
    },

    {
      id: 20,
      price: 50,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "5m",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 21,
      price: 100,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "10m",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 22,
      price: 150,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "15m",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 23,
      price: 200,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "20m",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 24,
      price: 250,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "25m",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 25,
      price: 300,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "30m",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 26,
      price: 1000,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "1h",
      priority: 40,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 27,
      price: 2000,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "2h",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 28,
      price: 3000,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "3h",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 29,
      price: 6000,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "6h",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },
    {
      id: 30,
      price: 12000,
      content: "دبل اكس بي تكست",
      description: "مضاعفة نقاط الخبرة من الرسائل",
      time: "12h",
      priority: 75,
      category: "text",
      emoji: "⌨️",
    },

    {
      id: 31,
      price: 350,
      content: "دبل رسائل",
      description: "مضاعفة الرسائل",
      time: "5m",
      priority: 50,
      category: "messages",
      emoji: "💬",
    },
    {
      id: 32,
      price: 350,
      content: "دبل رسائل",
      description: "مضاعفة الرسائل",
      time: "30m",
      priority: 50,
      category: "messages",
      emoji: "💬",
    },
    {
      id: 33,
      price: 350,
      content: "دبل دقائق",
      description: "مضاعفة دقائق الصوت",
      time: "5m",
      priority: 50,
      category: "minutes",
      emoji: "⏱️",
    },
    {
      id: 34,
      price: 350,
      content: "دبل دقائق",
      description: "مضاعفة دقائق الصوت",
      time: "30m",
      priority: 50,
      category: "minutes",
      emoji: "⏱️",
    },

    {
      id: 35,
      price: 150,
      content: "تخطي مهمة",
      description: "تجاوز مهمة لمرة واحدة",
      time: null,
      priority: 10,
      category: "special",
      emoji: "⏭️",
    },
  ],
  RANK_CONDITIONS: [
    { min: 100, max: 100, name: "Apex", image: "apex.png" },

    { min: 95, max: 99, name: "Epic III", image: "epic3.png" },
    { min: 90, max: 94, name: "Epic II", image: "epic2.png" },
    { min: 85, max: 89, name: "Epic", image: "epic.png" },

    { min: 80, max: 84, name: "Mythic III", image: "mythic3.png" },
    { min: 75, max: 79, name: "Mythic II", image: "mythic2.png" },
    { min: 70, max: 74, name: "Mythic", image: "mythic.png" },

    { min: 65, max: 69, name: "Emerald III", image: "emerald3.png" },
    { min: 60, max: 64, name: "Emerald II", image: "emerald2.png" },
    { min: 55, max: 59, name: "Emerald", image: "emerald.png" },

    { min: 50, max: 54, name: "Diamond III", image: "diamond3.png" },
    { min: 45, max: 49, name: "Diamond II", image: "diamond2.png" },
    { min: 40, max: 44, name: "Diamond", image: "diamond.png" },

    { min: 35, max: 39, name: "Gold III", image: "gold3.png" },
    { min: 30, max: 34, name: "Gold II", image: "gold2.png" },
    { min: 25, max: 29, name: "Gold", image: "gold.png" },

    { min: 20, max: 24, name: "Platinum III", image: "platinum3.png" },
    { min: 15, max: 19, name: "Platinum II", image: "platinum2.png" },
    { min: 12, max: 14, name: "Platinum", image: "platinum.png" },

    { min: 10, max: 11, name: "Silver III", image: "silver3.png" },
    { min: 8, max: 9, name: "Silver II", image: "silver2.png" },
    { min: 6, max: 7, name: "Silver", image: "silver.png" },

    { min: 5, max: 5, name: "Bronze III", image: "bronze3.png" },
    { min: 3, max: 4, name: "Bronze II", image: "bronze2.png" },
    { min: 1, max: 2, name: "Bronze", image: "bronze.png" },
  ],
};
